name: CI

on: [pull_request]

jobs:

  backend:
    name: lint + test
    runs-on: ubuntu-22.04

    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: install
      run: |
        python -m pip install -U pip
        pip install -e ".[dev]"
    - name: lint
      run: |
        make lint
    - name: test
      run: |
        make coverage
        coverage report
