name: CI

on: [pull_request]

jobs:

  backend:
    name: lint + test
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: install
      run: |
        python3 ./setup.py bdist_wheel
        export WHLNAME="./dist/rispy-0.CI-py3-none-any.whl"
        mv ./dist/*.whl $WHLNAME.
        pip install --upgrade "$WHLNAME[dev,test]"
    - name: lint
      run: |
        make lint
    - name: test
      run: |
        make test
