name: CI

on: [pull_request]

jobs:

  backend:
    name: lint + test
    runs-on: ubuntu-18.04

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: install
      run: |
        python3 -m pip install --upgrade setuptools setuptools_scm wheel pip
        python3 ./setup.py bdist_wheel
        export WHLNAME="./dist/rispy-0.CI-py3-none-any.whl"
        mv ./dist/*.whl $WHLNAME
        pip install --upgrade "$WHLNAME[dev,test]"
    - name: lint
      run: |
        make lint
    - name: test
      run: |
        make test
