name: Upload Python Package

on:
  workflow_dispatch:  # TODO - remove after testing
  push:

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "**/pyproject.toml"
    - name: Install dependencies
      run: uv sync --all-extras
    - name: Check linting
      run: uv run poe build
    - name: Publish Package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/  # TODO - remove after testing
